CREATE TABLE bugnet(
  id serial primary key,
  trait varchar
);
CREATE TABLE fishingpole(
  id serial primary key,
  trait varchar
);
CREATE TABLE animal(
  id serial primary key,
  species varchar,
  name varchar,
  bells integer,
  months varchar
);
CREATE TABLE ecosystem(
  id serial primary key,
  species varchar,
  name varchar,
  bells integer,
  months varchar
);
CREATE TABLE viewer(
  id serial primary key,
  username varchar,
  net integer references bugnet(id),
  pole integer references fishingpole(id),
  level integer,
  bells integer,
  turnips integer
);
CREATE TABLE pockets(
  id serial primary key,
  vid integer references viewer(id),
  aid integer references animal(id)
);
INSERT INTO bugnet VALUES
  (DEFAULT, 'Wooden'),
  (DEFAULT, 'Regular'),
  (DEFAULT, 'Silver'),
  (DEFAULT, 'Gold'),
  (DEFAULT, 'Platinum');

INSERT INTO fishingpole VALUES
  (DEFAULT, 'Wooden'),
  (DEFAULT, 'Regular'),
  (DEFAULT, 'Silver'),
  (DEFAULT, 'Gold'),
  (DEFAULT, 'Platinum');

INSERT INTO animal VALUES
  (DEFAULT,'bug','Common Butterfly',90,'CDEFI'),
  (DEFAULT,'bug','Yellow Butterfly',90,'CDEFI'),
  (DEFAULT,'bug','Tiger Butterfly',160,'CDEFGH'),
  (DEFAULT,'bug','Peacock Butterfly',220,'CDEFGHI'),
  (DEFAULT,'bug','Monarch Butterfly',90,'IJK'),
  (DEFAULT,'bug','Emperor Butterfly',2500,'FGHI'),
  (DEFAULT,'bug','Agrias Butterfly',3000,'FGHI'),
  (DEFAULT,'bug','Raja Brooke Butterfly',2500,'EFGHI'),
  (DEFAULT,'bug','Birdwing Butterfly',4000,'FGHI'),
  (DEFAULT,'bug','Moth',60,'EFGHI'),
  (DEFAULT,'bug','Oak Silk Moth',1200,'FGHI'),
  (DEFAULT,'bug','Honeybee',100,'CDEFG'),
  (DEFAULT,'bug','Bee',4500,'ABCDEFGHIJKL'),
  (DEFAULT,'bug','Long Locust',2500,'EFGHIJK'),
  (DEFAULT,'bug','Migratory Locust',3000,'HIJK'),
  (DEFAULT,'bug','Rice Grasshopper',2500,'HI'),
  (DEFAULT,'bug','Mantis',430,'DEFGHIJK'),
  (DEFAULT,'bug','Orchid Mantis',2400,'DEFGHIJK'),
  (DEFAULT,'bug','Brown Cicada',200,'HI'),
  (DEFAULT,'bug','Robust Cicada',300,'HI'),
  (DEFAULT,'bug','Giant Cicada',500,'HI'),
  (DEFAULT,'bug','Walker Cicada',400,'HIJ'),
  (DEFAULT,'bug','Evening Cicada',550,'HI'),
  (DEFAULT,'bug','Cicada Shell',100,'HI'),
  (DEFAULT,'bug','Lantern Fly',1800,'GHIJ'),
  (DEFAULT,'bug','Red Dragonfly',80,'IJ'),
  (DEFAULT,'bug','Darner Dragonfly',200,'FGH'),
  (DEFAULT,'bug','Banded Dragonfly',4500,'GH'),
  (DEFAULT,'bug','Petaltail Dragonfly',8000,'HIJ'),
  (DEFAULT,'bug','Ant',80,'ABCDEFGHIJKL'),
  (DEFAULT,'bug','Pondskater',130,'EFGHI'),
  (DEFAULT,'bug','Diving Beetle',800,'EFGHI'),
  (DEFAULT,'bug','Stinkbug',120,'DEFGHIJ'),
  (DEFAULT,'bug','Snail',250,'DEFGHI'),
  (DEFAULT,'bug','Cricket',130,'IJK'),
  (DEFAULT,'bug','Bell Cricket',430,'IJ'),
  (DEFAULT,'bug','Grasshopper',160,'GHI'),
  (DEFAULT,'bug','Mole Cricket',280,'ABCDEKL'),
  (DEFAULT,'bug','Walking Leaf',600,'GHI'),
  (DEFAULT,'bug','Walking Stick',600,'GHIJK'),
  (DEFAULT,'bug','Bagworm',300,'ABJKL'),
  (DEFAULT,'bug','Ladybug',200,'CDEFI'),
  (DEFAULT,'bug','Violin Beetle',250,'FIJK'),
  (DEFAULT,'bug','Longhorn Beetle',260,'FGH'),
  (DEFAULT,'bug','Tiger Beetle',1500,'CDEFGHIJ'),
  (DEFAULT,'bug','Dung Beetle',800,'ABL'),
  (DEFAULT,'bug','Wharf Roach',200,'ABCDEFGHIJKL'),
  (DEFAULT,'bug','Hermit Crab',1000,'ABCDEFGHIJKL'),
  (DEFAULT,'bug','Firefly',300,'F'),
  (DEFAULT,'bug','Fruit Beetle',100,'GHI'),
  (DEFAULT,'bug','Scarab Beetle',6000,'GH'),
  (DEFAULT,'bug','Jewel Beetle',2400,'GH'),
  (DEFAULT,'bug','Miyama Stag',1000,'GH'),
  (DEFAULT,'bug','Saw Stag Beetle',2000,'GH'),
  (DEFAULT,'bug','Giant Stag',10000,'GH'),
  (DEFAULT,'bug','Rainbow Stag',10000,'FGHI'),
  (DEFAULT,'bug','Cyclommatus',8000,'GH'),
  (DEFAULT,'bug','Golden Stag',12000,'GH'),
  (DEFAULT,'bug','Horned Dynastid',1350,'GH'),
  (DEFAULT,'bug','Horned Atlas',8000,'FGH'),
  (DEFAULT,'bug','Horned Elephant',8000,'GH'),
  (DEFAULT,'bug','Horned Hercules',12000,'GH'),
  (DEFAULT,'bug','Goliath Beetle',6000,'FGHI'),
  (DEFAULT,'bug','Flea',70,'CDEFGHIJK'),
  (DEFAULT,'bug','Pill Bug',250,'ABCDEFGHIJKL'),
  (DEFAULT,'bug','Mosquito',130,'FGHI'),
  (DEFAULT,'bug','Fly',60,'ABCDEFGHIJKL'),
  (DEFAULT,'bug','House Centipede',1000,'HIJ'),
  (DEFAULT,'bug','Centipede',300,'ABFGHIJKL'),
  (DEFAULT,'bug','Spider',300,'CDEFGHIJ'),
  (DEFAULT,'bug','Tarantula',8000,'FGH'),
  (DEFAULT,'bug','Scorpion',8000,'GHI'),
  (DEFAULT,'fish','Bitterling',900,'ABKL'),
  (DEFAULT,'fish','Pale Chub',160,'ABCDEFGHIJKL'),
  (DEFAULT,'fish','Crucian Carp',120,'ABCDEFGHIJKL'),
  (DEFAULT,'fish','Dace',200,'ABCDEFGHIJKL'),
  (DEFAULT,'fish','Barbel Steed',200,'ABCDEFGHIJKL'),
  (DEFAULT,'fish','Carp',300,'ABCDEFGHIJKL'),
  (DEFAULT,'fish','Koi',4000,'ABCDEFGHIJKL'),
  (DEFAULT,'fish','Goldfish',1300,'ABCDEFGHIJKL'),
  (DEFAULT,'fish','Popeyed Goldfish',1300,'ABCDEFGHIJKL'),
  (DEFAULT,'fish','Killifish',240,'DEFGH'),
  (DEFAULT,'fish','Crawfish',200,'DEFGHI'),
  (DEFAULT,'fish','Soft-Shelled Turtle',3750,'HI'),
  (DEFAULT,'fish','Tadpole',100,'CDEFG'),
  (DEFAULT,'fish','Frog',120,'EFGH'),
  (DEFAULT,'fish','Freshwater Goby',300,'ABCDEFGHIJKL'),
  (DEFAULT,'fish','Loach',300,'CDE'),
  (DEFAULT,'fish','Catfish',800,'EFGHI'),
  (DEFAULT,'fish','Eel',2000,'FGHI'),
  (DEFAULT,'fish','Giant Snakehead',5500,'FGH'),
  (DEFAULT,'fish','Bluegill',120,'ABCDEFGHIJKL'),
  (DEFAULT,'fish','Yellow Perch',240,'ABCJKL'),
  (DEFAULT,'fish','Black Bass',300,'ABCDEFGHIJKL'),
  (DEFAULT,'fish','Pike',1800,'IJKL'),
  (DEFAULT,'fish','Pond Smelt',300,'ABL'),
  (DEFAULT,'fish','Sweetfish',900,'GHI'),
  (DEFAULT,'fish','Cherry Salmon',1000,'CDEFJKL'),
  (DEFAULT,'fish','Char',3800,'CDEFJKL'),
  (DEFAULT,'fish','Rainbow Trout',300,'CDEFJKL'),
  (DEFAULT,'fish','Stringfish',15000,'ABL'),
  (DEFAULT,'fish','Salmon',700,'I'),
  (DEFAULT,'fish','King Salmon',1800,'HI'),
  (DEFAULT,'fish','Mitten Crab',2000,'JKL'),
  (DEFAULT,'fish','Guppy',1300,'DEFGHIJKL'),
  (DEFAULT,'fish','Nibble Fish',1200,'EFGHI'),
  (DEFAULT,'fish','Angelfish',3000,'EFGHIJ'),
  (DEFAULT,'fish','Neon Tetra',500,'DEFGHIJK'),
  (DEFAULT,'fish','Piranha',2500,'FGHI'),
  (DEFAULT,'fish','Arowana',10000,'FGHI'),
  (DEFAULT,'fish','Dorado',15000,'FGHI'),
  (DEFAULT,'fish','Gar',6000,'FGHI'),
  (DEFAULT,'fish','Arapaima',10000,'GHI'),
  (DEFAULT,'fish','Saddled Bichir',4000,'FGHI'),
  (DEFAULT,'fish','Sea Butterfly',1000,'ABL'),
  (DEFAULT,'fish','Seahorse',1100,'DEFGHIJK'),
  (DEFAULT,'fish','Clownfish',650,'DEFGHI'),
  (DEFAULT,'fish','Surgeonfish',1000,'DEFGHIL'),
  (DEFAULT,'fish','Butterfly Fish',1000,'DEFGHI'),
  (DEFAULT,'fish','Napoleonfish',10000,'GH'),
  (DEFAULT,'fish','Zebra Turkeyfish',400,'CDEFGHIJKL'),
  (DEFAULT,'fish','Blowfish',125,'ABKL'),
  (DEFAULT,'fish','Puffer Fish',240,'GHI'),
  (DEFAULT,'fish','Horse Mackerel',150,'ABCDEFGHIKL'),
  (DEFAULT,'fish','Barred Knifejaw',5000,'CDEFGHIKL'),
  (DEFAULT,'fish','Sea Bass',160,'ABCDEFGHIKL'),
  (DEFAULT,'fish','Red Snapper',3000,'ABCDEFGHIKL'),
  (DEFAULT,'fish','Dab',300,'ABCDJKL'),
  (DEFAULT,'fish','Olive Flounder',800,'ABCDEFGHIKL'),
  (DEFAULT,'fish','Squid',400,'ABCDEFGL'),
  (DEFAULT,'fish','Moray Eel',2000,'FGHIJ'),
  (DEFAULT,'fish','Ribbon Eel',600,'ABCDEFGHIKL'),
  (DEFAULT,'fish','Football Fish',2500,'ABCKL'),
  (DEFAULT,'fish','Tuna',7000,'ABCKL'),
  (DEFAULT,'fish','Blue Marlin',10000,'FGHI'),
  (DEFAULT,'fish','Giant Trevally',4500,'ABCDEFGHIJKL'),
  (DEFAULT,'fish','Ray',3000,'HIJK'),
  (DEFAULT,'fish','Ocean Sunfish',4000,'FGHI'),
  (DEFAULT,'fish','Hammerhead Shark',8000,'FGHI'),
  (DEFAULT,'fish','Shark',15000,'FGHI'),
  (DEFAULT,'fish','Saw Shark',12000,'FGHI'),
  (DEFAULT,'fish','Whale Shark',13000,'ABCDEFGHIJKL'),
  (DEFAULT,'fish','Oarfish',9000,'ABCDEL'),
  (DEFAULT,'fish','Coelacanth',15000,'ABCDEFGHIJKL');
